CREATE TABLE CIUDAD (
CIUDAD_ID VARCHAR2 (20) NOT NULL,
NOMBRE_CIUDAD VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_CIUDAD PRIMARY KEY (CIUDAD_ID)
);
COMMENT ON TABLE CIUDAD IS 'Es la entidad que contiene los datos de las ciudadades normalizadas.';
COMMENT ON COLUMN CIUDAD.CIUDAD_ID IS 'Es la la llave primaria de la tabla ciudad';
COMMENT ON COLUMN CIUDAD.NOMBRE_CIUDAD IS 'Es el nombre de la ciudad';

CREATE TABLE DIRECCION(
DIRECCION_ID VARCHAR2 (20) NOT NULL,
CALLE VARCHAR2 (3) NOT NULL,
CARRERA VARCHAR2 (3) NOT NULL,
NUMERO VARCHAR2 (3) NOT NULL,
ID_CIUDAD VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_DIRECCION PRIMARY KEY (DIRECCION_ID ),
CONSTRAINT FK_CIUDAD_EN_DIRECCION FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD (CIUDAD_ID) 
);
COMMENT ON TABLE DIRECCION IS 'Es la entidad que contiene los datos de las direcciones normalizadas.';
COMMENT ON COLUMN DIRECCION.DIRECCION_ID IS 'Es la la llave primaria de la tabla direccion';
COMMENT ON COLUMN DIRECCION.CALLE IS 'Es la calle normalizada de la direccion';
COMMENT ON COLUMN DIRECCION.CARRERA IS 'Es la carrera normalizada de la direccion';
COMMENT ON COLUMN DIRECCION.NUMERO IS 'Es el numero normalizado de la direccion';
COMMENT ON COLUMN DIRECCION.ID_CIUDAD IS 'Es la llave foranea que identifica la ciudad a la cual pertenece esa direccio.';


CREATE TABLE UNIVERSIDAD (
UNIVERSIDAD_ID VARCHAR2 (20) NOT NULL,
NOMBRE_UNIVERSIDAD VARCHAR2 (50) NOT NULL,
ID_DIRECCION VARCHAR2 (20) NOT NULL UNIQUE,
CONSTRAINT PK_UNIVERSIDAD PRIMARY KEY (UNIVERSIDAD_ID),
CONSTRAINT FK_DIRECCION_EN_UNIVERSIDAD FOREIGN KEY (DIRECCION_ID) REFERENCES DIRECCION (ID_DIRECCION)
);
COMMENT ON TABLE UNIVERSIDAD IS 'Es la entidad que contiene los datos de las universidades normalizadas.';
COMMENT ON COLUMN UNIVERSIDAD.UNIVERSIDAD_ID IS 'Es la la llave primaria de la tabla universidad';
COMMENT ON COLUMN UNIVERSIDAD.NOMBRE_UNIVERSIDAD IS 'Es el nombre de la universidad';
COMMENT ON COLUMN UNIVERSIDAD.DIRECCION_ID IS 'Es la llave foranea que identifica la direccion unica para la universidad.';

CREATE TABLE FACULTAD (
FACULTAD_ID VARCHAR2 (20) NOT NULL,
NOMBRE_FACULTAD VARCHAR2 (50) NOT NULL,
ID_UNIVERSIDAD VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_FACULTAD PRIMARY KEY (FACULTAD_ID),
CONSTRAINT FK_FACULTAD_EN_UNIVERSIDAD FOREIGN KEY (ID_UNIVERSIDAD) REFERENCES UNIVERSIDAD (UNIVERSIDAD_ID) 
);
COMMENT ON TABLE FACULTAD IS 'Es la entidad que contiene los datos de las facultades que tiene una universidad normalizadas.';
COMMENT ON COLUMN FACULTAD.FACULTAD_ID IS 'Es la la llave primaria de la tabla facultad';
COMMENT ON COLUMN FACULTAD.NOMBRE_FACULTAD IS 'Es el nombre de la facultad';
COMMENT ON COLUMN FACULTAD.ID_UNIVERSIDAD IS 'Es la llave foranea que identifica la universidad a la cual pertenece la facultad';


CREATE TABLE SECRETARIA(
SECRETARIA_ID VARCHAR2 (20) NOT NULL,
NOMBRE_SECRETARIA VARCHAR2 (35) NOT NULL,
APELLIDO_SECRETARIA VARCHAR2 (35) NOT NULL,
TELEFONO_SECRETARIA VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_SECRETARIA PRIMARY KEY (SECRETARIA_ID)
);
COMMENT ON TABLE SECRETARIA IS 'Es la entidad que contiene los datos de la tabla secretaria.';
COMMENT ON COLUMN SECRETARIA.SECRETARIA_ID IS 'Es la la llave primaria de la tabla secretaria';
COMMENT ON COLUMN SECRETARIA.NOMBRE_SECRETARIA IS 'Es el nombre de la secretaria';
COMMENT ON COLUMN SECRETARIA.APELLIDO_SECRETARIA IS 'Es el apellido de la secretaria';
COMMENT ON COLUMN SECRETARIA.TELEFONO_SECRETARIA IS 'Es el numero de telefono fijo o celular de la secretaria';

CREATE TABLE CONSEJO_CURRICULAR(
CONSEJO_CURRICULAR_ID VARCHAR2 (20) NOT NULL,
ID_SECRETARIA VARCHAR2 (20) NOT NULL UNIQUE,

CONSTRAINT PK_CONSEJO_CURRICULAR PRIMARY KEY (CONSEJO_CURRICULAR_ID),
CONSTRAINT FK_SECRETARIA_EN_CONSEJO FOREIGN KEY (ID_SECRETARIA) REFERENCES SECRETARIA (SECRETARIA_ID) 
);
COMMENT ON TABLE CONSEJO_CURRICULAR IS 'Es la entidad que contiene los datos de la tabla consejo curricular.';
COMMENT ON COLUMN CONSEJO_CURRICULAR.CONSEJO_CURRICULAR_ID IS 'Es la la llave primaria de la tabla consejo curricular';
COMMENT ON COLUMN CONSEJO_CURRICULAR.ID_SECRETARIA IS 'Es la llave foranea que identifica la secretaria adscrita al consejo curricular, es unica';

CREATE TABLE AREA (
AREA_ID VARCHAR2 (20) NOT NULL,
NOMBRE_AREA VARCHAR2 (50) NOT NULL,
CONSTRAINT PK_AREA PRIMARY KEY (AREA_ID),
);
COMMENT ON TABLE AREA IS 'Es la entidad que contiene los datos de las areas a la cual pertenecen los solictantes.';
COMMENT ON COLUMN AREA.AREA_ID IS 'Es la la llave primaria de la tabla area';
COMMENT ON COLUMN AREA.NOMBRE_AREA IS 'Es el nombre del area';

CREATE TABLE CARGO(
CARGO_ID VARCHAR2 (20) NOT NULL,
NOMBRE_CARGO VARCHAR2 (50) NOT NULL,
CONSTRAINT PK_CARGO PRIMARY KEY (CARGO_ID),
);
COMMENT ON TABLE CARGO IS 'Es la entidad que contiene los datos de los cargos que tienen los solictantes.';
COMMENT ON COLUMN CARGO.CARGO_ID IS 'Es la la llave primaria de la tabla cargo';
COMMENT ON COLUMN CARGO.NOMBRE_CARGO IS 'Es el nombre del cargo';

CREATE TABLE PROGRAMA_ACADEMICO (
PROGRAMA_ACADEMICO_ID VARCHAR2 (20) NOT NULL,
ID_FACULTAD VARCHAR2 (20) NOT NULL,
ID_CONSEJO_CURRICULAR VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_PROGRAMA_ACADEMICO PRIMARY KEY (PROGRAMA_ACADEMICO_ID),
CONSTRAINT FK_FACULTAD_EN_PROGRAMA FOREIGN KEY (ID_FACULTAD) REFERENCES FACULTAD (FACULTAD_ID),
CONSTRAINT FK_CONSEJO_CURRICULAR_EN_PROGRAMA FOREIGN KEY (ID_CONSEJO_CURRICULAR) REFERENCES CONSEJO_CURRICULAR(CONSEJO_CURRUCULAR_ID)
);
COMMENT ON TABLE PROGRAMA_ACADEMICO IS 'Es la entidad que contiene los datos del programa academico de una facultad';
COMMENT ON COLUMN PROGRAMA_ACADEMICO.PROGRAMA_ACADEMICO_ID IS 'Es la llave primaria de la tabla programa académico.';
COMMENT ON COLUMN PROGRAMA_ACADEMICO.ID_FACULTAD IS 'Es la llave foranea que identifica la facultad a la cual pertenece el programa.';
COMMENT ON COLUMN PROGRAMA_ACADEMICO.ID_CONSEJO_CURRICULAR IS 'Es la llave foranea que identifica el consejo curricular al cual pertenece el programa.';

CREATE TABLE SOLICITANTE (
SOLICITANTE_ID VARCHAR2 (20) NOT NULL,
NOMBRE_SOLICITANTE VARCHAR2 (35) NOT NULL,
APELLIDO_SOLICITANTE VARCHAR2 (35) NOT NULL,
TELEFONO_SOLICITANTE VARCHAR2 (20) NOT NULL,
ID_DIRECCION VARCHAR2 (20) NOT NULL,
ID_CARGO VARCHAR2 (20) NOT NULL,
ID_AREA VARCHAR2 (20) NOT NULL,
ID_CONSEJO_CURRICULAR VARCHAR2 (20),
ID_PROGRAMA_ACADEMICO VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_SOLICITANTE PRIMARY KEY (SOLICITANTE_ID),
CONSTRAINT FK_DIRECCION_EN_SOLICITANTE FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION (DIRECCION_ID),
CONSTRAINT FK_CARGO_EN_SOLICITANTE FOREIGN KEY (ID_CARGO) REFERENCES CARGO(CARGO_ID),
CONSTRAINT FK_AREA_EN SOLICITANTE FOREIGN KEY (ID_AREA) REFERENCES AREA (AREA_ID),
CONSTRAINT FK_CONSEJO_CURRICULAR_EN_SOLICITANTE FOREIGN KEY (ID_CONSEJO_CURRICULAR) REFERENCES CONSEJO_CURRICULAR (CONSEJO_CURRICULAR_ID),
CONSTRAINT FK_PROGRAMA_ACADEMICO_EN_SOLICITANTE FOREIGN KEY (ID_PROGRAMA_ACADEMICO) REFERENCES PROGRAMA_ACADEMICO (PROGRAMA_ACADEMICO_ID)
);
COMMENT ON TABLE SOLICITANTE IS 'Es la entidad que contiene los datos del solicitante que es el que descubre las necesidades de auxiliares .';
COMMENT ON COLUMN SOLICITANTE.SOLICITANTE_ID IS 'Es la llave primaria de la tabla solicitante';
COMMENT ON COLUMN SOLICITANTE.NOMBRE_SOLICITANTE IS 'Es el nombre del solicitante';
COMMENT ON COLUMN SOLICITANTE.APELLIDO_SOLICITANTE IS 'Es elapellido del solicitante';
COMMENT ON COLUMN SOLICITANTE.TELEFONO_SOLICITANTE IS 'Es el telefono del solicitante';
COMMENT ON COLUMN SOLICITANTE.ID_DIRECCION IS 'Es la llave foranea que identifica la direccion del solicitante';
COMMENT ON COLUMN SOLICITANTE.ID_CARGO  IS 'Es la llave foranea que identifica el cargo que ocupa el solicitante';
COMMENT ON COLUMN SOLICITANTE.ID_AREA  IS 'Es la llave foranea que identifica el area a la cual pertenece el solicitante';
COMMENT ON COLUMN SOLICITANTE.ID_CONSEJO_CURRICULAR  IS 'Es la llave foranea que identifica el consejo curricular al cual puede o no pertencer un solicitante';
COMMENT ON COLUMN SOLICITANTE.ID_PROGRAMA_ACADEMICO IS 'Es la llave foranea que identifica el eprograma academico al cual pertenece el solicitante.';

CREATE TABLE JORNADA (
JORNADA_ID VARCHAR2 (20) NOT NULL,
NOMBRE_JORNADA VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_JORNADA PRIMARY KEY (JORNADA_ID)
);
COMMENT ON TABLE JORNADA IS 'Es entidad que contiene los datos de la jornada en la cual se desempeña un director de programa';
COMMENT ON COLUMN JORNADA.JORNADA_ID IS 'Es la llave primara de la tabla jornada';
COMMENT ON COLUMN JORNADA.NOMBRE_JORNADA IS 'Es el nombre de la jornada del programa academico (nocturno, diurno, a distancia).';

CREATE TABLE DIRECTORES (
ID_PROGRAMA VARCHAR2 (20) NOT NULL,
ID_SOLICITANTE VARCHAR2 (20) NOT NULL UNIQUE,
ID_JORNADA VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_DIRECTORES PRIMARY KEY (ID_PROGRAMA, ID_JORNADA),
CONSTRAINT FK_PROGRAMA_EN_DIRECTORES FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA_ACADEMICO (PROGRAMA_ACADEMICO_ID),
CONSTRAINT FK_SOLICITANTE_EN_DIRECTORES FOREIGN KEY (ID_SOLICITANTE)REFERENCES SOLICITANTE (SOLICITANTE_ID),
CONSTRAINT FK_JORNADA_EN_DIRECTORES FOREIGN KEY (ID_JORNADA) REFERENCES JORNADA (JORNADA_ID)
);
COMMENT ON TABLE DIRECTORES IS 'Es la entidad puente que contiene los datos de los directores de programa';
COMMENT ON COLUMN DIRECTORES.ID_PROGRAMA IS 'Es la llave foranea que ientifica el programa al cual pertenece el director';
COMMENT ON COLUMN DIRECTORES.ID_SOLICITANTE  IS 'Es la llave foranea que identifica el nombre del director, el cual a su vez puede ser un solicitante';
COMMENT ON COLUMN DIRECTORES.ID_JORNADA IS 'Es la llave forane a que identifica la jornada del programa que dirige el solicitante';


CREATE TABLE AUXILIAR(
AUXILIAR_ID VARCHAR2 (20) NOT NULL,
CODIGO_AUXILIAR VARCHAR2 (20) NOT NULL,
NOMBRE_AUXILIAR VARCHAR2 (35) NOT NULL,
APELLIDO_AUXILIAR VARCHAR2 (35) NOT NULL,
TELEFONO_AUXILIAR VARCHAR2 (20) NOT NULL,
ID_DIRECCION VARCHAR2 (20) NOT NULL,
ID_PROGRAMA_ACADEMICO VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_AUXILIAR PRIMARY KEY (AUXILIAR_ID),
CONSTRAINT FK_DIRECCION_EN_AUXILIAR FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION (DIRECCION_ID),
CONSTRAINT FK_PROGRAMA_ACADEMICO_EN_AUXILIAR FOREIGN KEY (ID_PROGRAMA_ACADEMICO) REFERENCES PROGRAMA_ACADEMICO (PROGRAMA_ACADEMICO_ID)
);
COMMENT ON TABLE AUXILIAR IS 'Es la entidad que contiene los datos del auxiliar o estudiante que postula o puede observar las convocatorias.';
COMMENT ON COLUMN AUXILIAR.AUXILIAR_ID IS 'Es la llave primaria de la tabla, es distinto al codigo';
COMMENT ON COLUMN AUXILIAR.CODIGO_AUXILIAR IS 'Es la identificacion del auxiliar (cedula o tarjeta de identidad)';
COMMENT ON COLUMN AUXILIAR.NOMBRE_AUXILIAR IS 'Es el nombre del auxiliar';
COMMENT ON COLUMN AUXILIAR.APELLIDO_AUXILIAR IS 'Es el apellido del auxiliar';
COMMENT ON COLUMN AUXILIAR.TELEFONO_AUXILIAR IS 'Es el telefono del auxiliar';
COMMENT ON COLUMN AUXILIAR.ID_DIRECCION IS 'Es el la llave foranea que identifica la direccion que tiene el auxiliar';
COMMENT ON COLUMN AUXILIAR.ID_PROGRAMA_ACADEMICO IS 'Es la llave foranea que identifica el programa académico al que pertenece el auxiliar';

CREATE TABLE TIPO_REQUISITO (
TIPO_REQUISITO_ID VARCHAR2 (20) NOT NULL,
DESCRIPCION_TIPO_REQUISITO VARCHAR2 (255) NOT NULL,
CONSTRAINT PK_TIPO_REQUISITO PRIMARY KEY (REQUISITO_ID),
);
COMMENT ON TABLE TIPO_REQUISITO IS 'Es la entidad que contiene los datos de los tipos de requisitos de una convocatoria (general, especificos)';
COMMENT ON COLUMN TIPO_REQUISITO.TIPO_REQUISITO_ID IS 'Es la llave primaria de la tabla tipo requisito.';
COMMENT ON COLUMN TIPO_REQUISITO.DESCRIPCION_TIPO_REQUISITO IS 'Es la descripcion del tipo de requisito.';

CREATE TABLE REQUISITO (
REQUISITO_ID VARCHAR2 (20) NOT NULL,
DESCRIPCION_REQUISITO VARCHAR2 (255) NOT NULL,
ID_TIPO_REQUISITO VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_REQUISITO PRIMARY KEY (REQUISITO_ID),
CONSTRAINT FK_TIPO_REQUISITO_EN_REQUISITO FOREIGN KEY (ID_TIPO_REQUISITO) REFERENCES TIPO_REQUISITO(TIPO_REQUISITO_ID)
); 
COMMENT ON TABLE REQUISITO IS 'En la entidad que contiene los datos de los requisitos necesarios de una convocatoria.';
COMMENT ON COLUMN REQUISITO.DESCRIPCION_REQUISITO IS 'Es la desripcion del requisito';
COMMENT ON COLUMN REQUISITO.ID_TIPO_REQUISITO IS 'Es la llave foranea que identifica el tipo de requisito al cual pertenece un requisito.';

CREATE TABLE SOLICITUD_AUXILIARES(
SOLICITUD_AUXILIARES_ID VARCHAR2 (20) NOT NULL,
CANTIDAD_AUXILIARES NUMBER (2,0) NOT NULL,
CANTIDAD_HORAS NUMBER (3,0) NOT NULL,
DESCRIPCION_SOLICITUD_AUXILIARES VARCHAR (255) NOT NULL,
FECHA_CREACION DATE NOT NULL,
ID_SOLICITANTE VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_SOLICITUD_AUXILIARES PRIMARY KEY (SOLICITUD_AUXILIARES_ID),
CONSTRAINT FK_SOLICITANTE_EN_SOLICITUD_AUXILIARES FOREIGN KEY (ID_SOLICITANTE) REFERENCES SOLICITANTE (SOLICITANTE_ID)
);
COMMENT ON TABLE SOLICITUD_AUXILIARES IS 'Es la entidad que contiene los datos de las solicitudes de auxiliares.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.SOLICITUD_AUXILIARES_ID IS 'Es la llave primaria de la tabla colicitud auxiliares';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.CANTIDAD_AUXILIARES IS 'Es la cantidad de auxiliares requeridos.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.CANTIDAD_HORAS IS 'Es la cantiidad de horas requeridas por cada auxiliar.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.DESCRIPCION_SOLICITUD_AUXILIARES IS 'Es la descripcion de una solicitud de auxiliiares.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.FECHA_CREACION IS 'Es la fecha de creacion de la solicitud.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.ID_SOLICITANTE IS 'Es la llave foranea que identifica el solicitante que crea la solicitud.';

CREATE TABLE SOLICITUD_AUXILIARES_REQUISITOS(
ID_REQUISITOS VARCHAR2 (20) NOT NULL,
ID_SOLICITUD_AUXILIARES VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_SOLICITUD_AUXILIARES_REQUISITOS PRIMARY KEY (ID_REQUISITOS, ID_SOLICITUD_AUXILIARES),
CONSTRAINT FK_REQUISITOS_EN_SOLICITUD_AUXILIARES_REQUISITOS FOREIGN KEY (ID_REQUISITOS) REFERENCES REQUISITOS (REQUISITOS_ID),
CONSTRAINT FK_SOLICITUD_AUXILIARES_EN_SOLICITUD_AUXILIARES_REQUISITOS FOREIGN KEY (ID_SOLICITUD_AUXILIARES) REFERENCES SOLICITUD_AUXILIARES(SOLICITUD_AUXILIARES_ID)
);
COMMENT ON TABLE SOLICITUD_AUXILIARES_REQUISITOS IS 'Es la entidad puente entre las solicitudes de auxiliares y los requisitos.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES_REQUISITOS.ID_REQUISITOS IS 'Es la llave foranea que identifica un requisito dentro de la solicitud.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES_REQUISITOS.ID_SOLICITUD_AUXILIARES IS 'Es la llave foranea que identifica la solicitud de auxiliares.';

CREATE TABLE CONVOCATORIA (
CONVOCATORIA_ID VARCHAR2 (20) NOT NULL,
INFORMACION_ADICIONAL_CONVOCATORIA VARCHAR2 (255) NOT NULL,
FECHA_CREACION DATE NOT NULL,
FECHA_APERTURA DATE NOT NULL,
FECHA_CIERRE DATE NOT NULL,
FECHA_PRUEBA DATE,
ID_TIPO_AUXILIAR VARCHAR (20) NOT NULL,
ID_PROGRAMA_ACADEMICO VARCHAR2 (20) NOT NULL,
ID_SOLICITUD_AUXILIARES VARCHAR (20) UNIQUE NOT NULL,
CONSTRAINT PK_CONVOCATORIA PRIMARY KEY (CONVOCATORIA_ID),
CONSTRAINT FK_TIPO_AUXILIAR_EN_CONVOCATORIA FOREIGN KEY (ID_TIPO_AUXILIAR) REFERENCES TIPO_AUXILIAR (TIPO_AUXILIAR_ID),
CONSTRAINT FK_PROGRAMA_ACADEMICO_EN_CONVOCATORIA FOREIGN KEY (ID_PROGRAMA_ACADEMICO) REFERENCES PROGRAMA_ACADEMICO (ID_PROGRAMA_ACADEMICO),
CONSTRAINT FK_SOLICITUD_AUXILIARES_EN_CONVOCATORIA FOREIGN KEY (ID_SOLICITUD_AUXILIARES) REFERENCES SOLICITUD_AUXILIARES (SOLICITUD_AUXILIARES_ID)
);
COMMENT ON TABLE CONVOCATORIA IS 'Es la entidad que contiene los datos de las convocatorias';
COMMENT ON COLUMN CONVOCATORIA.CONVOCATORIA_ID IS 'Es la llave primaria de la tabla convocatoria';
COMMENT ON COLUMN CONVOCATORIA.INFORMACION_ADICIONAL_CONVOCATORIA IS 'Es la informacion adicional perinente a la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.FECHA_CREACION IS 'Es la fecha de creacion en la base de datos de la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.FECHA_APERTURA IS 'Es la fecha de apertura de la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.FECHA_CIERRE IS 'Es la fecha de cierre de la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.FECHA_PRUEBA IS 'Es la fecha de prueba de la convocatoria, si aplica o no, puede ser null';
COMMENT ON COLUMN CONVOCATORIA.ID_TIPO_AUXILIAR IS 'Es la llave foranea que identifica el tipo de auxiliar que por el cual se abre la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.ID_PROGRAMA_ACADEMICO IS 'Es la llave foranea que identifica el programa academico que necesita el auxiliar por el cual abre la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.ID_SOLICITUD_AUXILIARES IS 'Es la llave foranea que identifica la solicitud relacionada a la convocatoria';

CREATE TABLE CONVOCATORIA_REQUISITOS (
ID_REQUISITOS VARCHAR2 (20) NOT NULL,
ID_CONVOCATORIA VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_CONVOCATORIA_REQUISITOS PRIMARY KEY (ID_REQUISITOS, ID_CONVOCATORIA),
CONSTRAINT FK_REQUISITOS_EN_CONVOCATORIA_REQUISITOS FOREIGN KEY (ID_REQUISITOS) REFERENCES REQUISITOS (REQUISITOS_ID),
CONSTRAINT FK_CONVOCATORIA_EN_CONVOCATORIA_REQUISITOS FOREIGN KEY (ID_CONVOCATORIA) REFERENCES CONVOCATORIA (CONVOCATORIA_ID)
);
COMMENT ON TABLE CONVOCATORIA_REQUISITOS IS 'Es la entidad puente que contiene los datos de convocatoria y requisitos.';
COMMENT ON COLUMN CONVOCATORIA_REQUISITOS.ID_REQUISITOS IS 'Es la llave foranea que identifica los requisitos generales o especificos necesarios en la convocatoria';
COMMENT ON COLUMN CONVOCATORIA_REQUISITOS.ID_CONVOCATORIA IS 'Es la llave foranea que identifica la convocatoria a la que se le van a aplicar los requisitos';

CREATE TABLE DOCUMENTO_EVALUACION (
DOCUMENTO_EVALUACION_ID VARCHAR2 (20) NOT NULL,
SOLICITANTE_ID 

);




/*oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
/* CONVENCIONES 
  TABLAS DE MAS DE 2 PALABRAS SE UTILIZAN LAS 3 PRIMERAS LETRAS DE CADA PALABRA PARA LA LLAVE PRIMARIA
  
  PARA LAS LLAVES FORANEAS SE UTILIZA LA SIGUIENTE SINTAXIS (CAMBIAR LO QUE ESTA EN MINUSCULA):
  FK_nombreTablaForanea_EN_TablaActual
  
*/


--
CREATE TABLE TIPO_AUXILIAR (
TIPO_AUXILIAR_ID VARCHAR2 (20) NOT NULL,
DESCRIPCION_TIPO_AUXILIAR VARCHAR2 (255) NOT NULL,

CONSTRAINT PK_TIPO_AUXILIAR PRIMARY KEY (TIP_AUX_ID)
);
COMMENT ON TABLE TIPO_AUXILIAR IS 'Es la entidad que contiene los datos del tipo auxiliar (docencia, administrativos, monitor... entre otros que se requieran).';
COMMENT ON COLUMN TIPO_AUXILIAR.TIPO_AUXILIAR_ID IS 'Es la llave primaria de la tabla Tipo auxiliar';
COMMENT ON COLUMN TIPO_AUXILIAR.DESCRIPCION_TIPO_AUXILIAR IS 'Es la descripción de la tabla tipo auxiliar';

--
CREATE TABLE HORARIO_ACTIVIDADES (
HORARIO_ACTIVIDADES_ID VARCHAR2 (20) NOT NULL,
FECHA_CREACION_HORARIO_ACTIVIDADES DATE NOT NULL,
ID_TIPO_AUXILIAR VARCHAR2 (20),
ID_AUXILIAR VARCHAR2 (20) NOT NULL,

CONSTRAINT PK_HORARIO_ACTIVIDADES PRIMARY KEY (HOR_ID),
CONSTRAINT FK_TIPO_AUXILIARES_EN_HORARIO_ACTIVIDADES FOREIGN KEY (ID_TIPO_AUX) REFERENCES TIPO_AUXILIAR (TIP_AUX), 
CONSTRAINT FK_ID_AUXILIAR_EN_HORARIO_ACTIVIDADES FOREIGN KEY (ID_AUXILIAR) REFERENCES AUXILIAR (AUX_ID)
);

COMMENT ON TABLE HORARIO_ACTIVIDADESIS 'Es la entidad que contiene los datos del horario del auxiliar.';
COMMENT ON COLUMN HORARIO_ACTIVIDADES.HORARIO_ACTIVIDADES_ID  IS 'Es la llave primaria de la tabla horario auxiliar.';
COMMENT ON COLUMN HORARIO_ACTIVIDADES.FECHA_CREACION_HORARIO_ACTIVIDADES IS 'Es la fecha de cración del horario de actividades';
COMMENT ON COLUMN HORARIO_ACTIVIDADES.ID_TIPO_AUXILIAR IS 'Es el campo que identifica la llave foranea de la tabla tipo auxiliar';
COMMENT ON COLUMN HORARIO_ACTIVIDADES.ID_AUXILIAR IS 'Es el campo que identifica la llave foranea de la tabla auxiliar';

--

CREATE TABLE FECHA_HORARIO (
FECHA_HORARIO_ID VARCHAR2 (20) NOT NULL,
FECHA_FECHA_HORARIO DATE NOT NULL,
ID_HORARIO_ACTIVIDADES VARCHAR2 (20) NOT NULL,

CONSTRAINT PK_FECHA_HORARIO PRIMARY KEY (FEC_HOR_ID),
CONSTRAINT FK_HORARIO_ACTIVIDADES_EN_FECHA_HORARIO FOREIGN KEY (ID_HOR_ACT) REFERENCES HORARIO_ACTIVIDADES (HOR_ACT_ID)
);


COMMENT ON TABLE FECHA_HORARIO  IS 'Es la entidad que contiene los datos de la fecha de el horario (dia que realiza la actividad).';
COMMENT ON COLUMN FECHA_HORARIO.FECHA_HORARIO_ID IS 'Es la llave primaria de la tabla fecha horario.';
COMMENT ON COLUMN FECHA_HORARIO.FECHA_FECHA_HORARIO IS 'Es la fecha de realizacion de las actividades';
COMMENT ON COLUMN FECHA_HORARIO.ID_HORARIO_ACTIVIDADES IS 'Es el campo que identifica la llave foranea de la tabla horario de actividades.';

--


CREATE TABLE HORA (
HORA_ID VARCHAR2 (20) NOT NULL,
HORA_INICIO VARCHAR2 (20) NOT NULL,
HORA_FIN VARCHAR2 (20) NOT NULL,
ID_FECHA_HORARIO VARCHAR2 (20) NOT NULL,

CONSTRAINT PK_HORA PRIMARY KEY (HOR_ID),
CONSTRAINT FK_FECHA_HORARIO_EN_HORA FOREIGN KEY (ID_FECHA_HORARIO) REFERENCES FECHA_HORARIO (FEC_HOR_ID)
);

COMMENT ON TABLE HORA IS 'Es la entidad que contiene las horas asignadas o concordadas con el auxiliar para realizar las actividades.';
COMMENT ON COLUMN HORA.HORA_ID  IS 'Es la llave primaria de la tabla hora.';
COMMENT ON COLUMN HORA.HORA_INICIO IS 'Es el campo que identifica la hora de unicio de las actividades.';
COMMENT ON COLUMN HORA.HORA_FIN IS 'Es el campo que identifica la hora de finalización de las actividades.';
COMMENT ON COLUMN HORA.ID_FECHA_HORARIO IS 'Es el campo que identifica la llave foranea de la tabla fecha horario.';

--

CREATE TABLE CUMPLIMIENTO_ACTIVIDADES(
CUMPLIMIENTO_ACTIVIDADES_ID VARCHAR2 (20) NOT NULL,
DESCRIPCION_CUMPLIMIENTO_ACTIVIDADES VARCHAR2 (255) NOT NULL,
FECHA_CREACION_CUMPLIMIENTO_ACTIVIDADES DATE NOT NULL,
ID_SOLICITANTE VARCHAR2 (20) NOT NULL,

CONSTRAINT PK_CUMPLIMIENTO_ACTIVIDADES PRIMARY KEY (CUMPLIMIENTO_ACTIVIDADES),
CONSTRAINT FK_SOLICITANTE_EN_CUMPLIMIENTO_ACTIVIDADES FOREIGN KEY (ID_SOLICITANTE) REFERENCES SOLICITANTE (SOLICITANTE_ID)
);

COMMENT ON TABLE CUMPLIMIENTO_ACTIVIDADES IS 'Es la entidad que contiene el cumplimiento de las actividades del auxiliar.';
COMMENT ON COLUMN CUMPLIMIENTO_ACTIVIDADES.CUMPLIMIENTO_ACTIVIDADES_ID IS 'Es la llave primaria de la tabla cumplimieto actividades.';
COMMENT ON COLUMN CUMPLIMIENTO_ACTIVIDADES.DESCRIPCION_CUMPLIMIENTO_ACTIVIDADES IS 'Es el campo que identifica a la descripcion del cumplimiento de activiades.';
COMMENT ON COLUMN CUMPLIMIENTO_ACTIVIDADES.FECHA_CREACION_CUMPLIMIENTO_ACTIVIDADES IS 'Es el campo que identifica a la fecha de creación del cumplimiento.';
COMMENT ON COLUMN CUMPLIMIENTO_ACTIVIDADES.ID_SOLICITANTE IS 'Es el campo que identifica la llave foranea de la tabla solicitante.';

----

CREATE TABLE AUXILIAR_CUMPLIMIENTO_ACTIVIDADES(
ID_AUXILIAR VARCHAR2 (20) NOT NULL,
ID_CUMPLIMIENTO_ACTIVIDADES VARCHAR2 (20) NOT NULL,
ID_TIPO_AUXILIAR VARCHAR2 (20) NOT NULL,

CONSTRAINT FK_AUXILIAR_EN_AUXILIAR_CUMPLIMIENTO_ACTIVIDADES FOREIGN KEY (ID_AUXILIAR) REFERENCES AUXILIAR (AUXILIAR_ID),
CONSTRAINT FK_CUMPLIENTO_ACTIVIDADES_EN_AUXILIAR_CUMPLIMIENTO_ACTIVIDADES FOREIGN KEY (ID_CUMPLIMIENTO_ACTIVIDADES) REFERENCES CUMPLIMIENTO_ACTIVIDADES (CUMPLIMIENTO_ACTIVIDADES_ID),
CONSTRAINT FK_TIPO_AUXILIAR_EN_AUXILIAR_CUMPLIMIENTO_ACTIVIDADES FOREIGN KEY (ID_TIPO_AUXILIAR) REFERENCES TIPO_AUXILIAR (TIPO_AUXILIAR_ID)
);

COMMENT ON TABLE AUXILIAR_CUMPLIMIENTO_ACTIVIDADES IS 'Es la entidad PUENTE que representa el auxiliar con el cumplimiento de actividades.';
COMMENT ON COLUMN AUXILIAR_CUMPLIMIENTO_ACTIVIDADES.ID_AUXILIAR IS 'Es el campo que identifica la llave foranea de la tabla auxiliar.';
COMMENT ON COLUMN AUXILIAR_CUMPLIMIENTO_ACTIVIDADES.ID_CUMPLIMIENTO_ACTIVIDADES IS 'Es el campo que identifica la llave foranea de la tabla cumplimiento de actividades.';
COMMENT ON COLUMN AUXILIAR_CUMPLIMIENTO_ACTIVIDADES.ID_TIPO_AUXILIAR IS 'Es el campo que identifica la llave foranea de la tabla tipo de solicitante.';



--

CREATE TABLE RESOLUCION_AUXILIARES_SELECCIONADOS(
RESOLUCION_AUXILIARES_SELECCIONADOS_ID VARCHAR2 (20) NOT NULL,
DESCRIPCION_RESOLUCION_AUXILIARES_SELECCIONADOS VARCHAR2 (255) NOT NULL,
FECHA_CREACION_RESOLUCION_AUXILIARES_SELECCIONADOS DATE NOT NULL,
ID_SOLICITANTE VARCHAR2 (20) NOT NULL,

CONSTRAINT PK_RESOLUCION_AUXILIARES_SELECCIONADOS PRIMARY KEY (RESOLUCION_AUXILIARES_SELECCIONADOS_ID),
CONSTRAINT FK_SOLICITANTE_EN_RESOLUCION_AUXILIARES_SELECCIONADOS FOREIGN KEY (ID_SOLICITANTE) REFERENCES SOLICITANTE (SOLICITANTE_ID)
);


COMMENT ON TABLE RESOLUCION_AUXILIARES_SELECCIONADOS IS 'Es la entidad que representa la resolucion de auxiliares seleccionados.';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECCIONADOS.RESOLUCION_AUXILIARES_SELECCIONADOS_ID IS 'Es la llave primaria de la tabla resolucion de auxiliares seleccionados.';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECCIONADOS.DESCRIPCION_RESOLUCION_AUXILIARES_SELECCIONADOS IS 'Es el campo que identifica a la descripcion de la resolucion de auxiliares seleccionados.';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECCIONADOS.FECHA_CREACION_RESOLUCION_AUXILIARES_SELECCIONADOS IS 'Es el campo que identifica a la fecha decreacion de la resolucion de auxiliares seleccionados.';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECCIONADOS.ID_SOLICITANTE IS 'Es el campo que identifica la llave foranea de la tabla tipo de solicitante.';


---


CREATE TABLE DETALLE_RESOLUCION(
PROMEDIO_AUXILIAR_DETALLE_RESOLUCION NUMBER (2,2)  

);














/*************************************************************************************************************************/
/********************************PARA BORRAR ****************************************************************************/
CREATE TABLE AUXILIAR(
AUX_ID VARCHAR22 (20) NOT NULL,
NOMBRE_AUX VARCHAR22 (50) NOT NULL,
APELLIDO_AUX VARCHAR22 (50) NOT NULL,
TELEFONO_AUX VARCHAR22 (20) NOT NULL, -- Falta normalizar Direccion, Programa académico--
CONSTRAINT PK_AUXILIAR PRIMARY KEY (AUX_ID)
);

COMMENT ON TABLE AUXILIAR IS 'Es la entidad que contiene los datos del auxiliar o estudiante que postula o puede observar las convocatorias.';
COMMENT ON COLUMN AUXILIAR.AUX_ID IS 'Es la identificacion del auxiliar y la llave primaria';
COMMENT ON COLUMN AUXILIAR.NOMBRE_AUX IS 'Es el nombre del auxiliar';
COMMENT ON COLUMN AUXILIAR.APELLIDO_AUX IS 'Es el apellido del auxiliar';
COMMENT ON COLUMN AUXILIAR.TELEFONO_AUX IS 'Es el telefono del auxiliar';

CREATE TABLE SOLICITANTE (
SOL_ID VARCHAR22 (20) NOT NULL,
NOMBRE_SOL VARCHAR22 (50) NOT NULL,
APELLIDO_SOL VARCHAR22 (50) NOT NULL,
TELEFONO_SOL VARCHAR22 (20) NOT NULL,--Falta normalizar area - Cargo - Direccion
CONSTRAINT PK_SOL PRIMARY KEY (SOL_ID),
);
COMMENT ON TABLE SOLICITANTE IS 'Es la entidad que contiene los datos del solicitante quien describe la necesidad del auxiliar.';
COMMENT ON COLUMN SOLICITANTE.SOL_ID IS 'Es la identificacion del solicitante y la llave primaria';
COMMENT ON COLUMN SOLICITANTE.NOMBRE_SOL IS 'Es el nombre del solicitante';
COMMENT ON COLUMN SOLICITANTE.APELLIDO_SOL IS 'Es el apellido del solicitante';
COMMENT ON COLUMN SOLICITANTE.TELEFONO_SOL IS 'Es el telefono del solicitante';

CREATE TABLE PROGRAMA_ACADEMICO(
  PRO_ACA_ID VARCHAR22(20) NOT NULL,
  NOMBRE_PRO_ACA VARCHAR22(50) NOT NULL,
  ID_FACULTAD VARCHAR22(2) NOT NULL,
  
  CONSTRAINT PK_PROGRAMA_ACADEMICO PRIMARY KEY (PRO_ACA_ID),
  CONSTRAINT FK_FACULTAD_EN_PROGRAMA_ACADEMICO FOREIGN KEY (ID_FACULTAD) REFERENCES FACULTAD (FACULTAD_ID)
);

CREATE TABLE FACULTAD(
  FACULTAD_ID VARCHAR22(2) NOT NULL,
  NOMBRE_FACULTAD VARCHAR22(50) NOT NULL,
  ID_UNIVERSIDAD VARCHAR22(5) NOT NULL,
  
  CONSTRAINT PK_FACULTAD PRIMARY KEY (ID_UNIVERSIDAD),
  CONSTRAINT FK_UNIVERSIDAD_EN_FACULTAD FOREIGN KEY (ID_UNIVERSIDAD) REFERENCES UNIVERSIDAD (UNIVERSIDAD_ID)
);


CREATE TABLE UNIVERSIDAD(
  UNIVERSIDAD_ID VARCHAR2 (20) NOT NULL,
  NOMBRE_UNIVERSIDAD VARCHAR2 (20) NOT NULL,
  
  CONSTRAINT PK_UNIVERSIDAD PRIMARY KEY (UNIVERSIDAD_ID)
);


<<<<<<< HEAD
=======
CREATE TABLE HORARIO_ACTIVIDADES (
HOR_ACT_ID VARCHAR2 (20) NOT NULL,
FECHA_CREACION_HOR_ACT DATE NOT NULL,
ID_TIPO_AUX VARCHAR2 (20),
ID_AUXILIAR VARCHAR2 (20) NOT NULL,
>>>>>>> ce9a384960d2d8c6bd34ad1a5391b8ad6a1c0ebc





<<<<<<< HEAD




=======
CREATE TABLE FECHA_HORARIO (
FEC_HOR_ID VARCHAR2 (20) NOT NULL,
FECHA_FEC_HOR DATE NOT NULL,
ID_HOR_ACT VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_FECHA_HORARIO PRIMARY KEY (FEC_HOR_ID),
CONSTRAINT FK_HORARIO_ACTIVIDADES_EN_FECHA_HORARIO FOREIGN KEY (ID_HOR_ACT) REFERENCES HORARIO_ACTIVIDADES (HOR_ACT_ID)
);

CREATE TABLE HORA (
HOR_ID VARCHAR2 (20) NOT NULL,
HORA_INICIO VARCHAR2 (20) NOT NULL,
HORA_FIN VARCHAR2 (20) NOT NULL,
ID_FECHA_HORARIO VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_HORA PRIMARY KEY (HOR_ID),
CONSTRAINT FK_FECHA_HORARIO_EN_HORA FOREIGN KEY (ID_FECHA_HORARIO) REFERENCES FECHA_HORARIO (FEC_HOR_ID)
);

CREATE TABLE TIPO_AUXILIAR (
TIP_AUX_ID VARCHAR2 (20) NOT NULL,
DESCRIPCION_TIP_AUX VARCHAR2 (30) NOT NULL,
CONSTRAINT PK_TIPO_AUXILIAR PRIMARY KEY (TIP_AUX_ID)
);
>>>>>>> ce9a384960d2d8c6bd34ad1a5391b8ad6a1c0ebc

RESOLUCION_AUXILIARES_SELECICONADOS(
RESOLUCION_ID VARCHAR2 (20) NOT NULL
DESCRIPCION VARCHAR2 (255) NOT NULL,
ID_TIPO_AUXILIAR VARCHAR2 (20) NOT NULL,
ID_AUXILIAR VARCHAR22 (20) NOT NULL,
PROMEDIO_AUXILIAR VARCHAR2 (20) NOT NULL,
HORAS_SEMESTRALES VARCHAR2 (2) NOT NULL,
VALOR_A_PAGAR VARCHAR2 (7) NOT NULL,
NOMBRE_SOLICITANTE VARCAHR (35) NOT NULL,
NOMBRE_DIRECTOR_PROGRAMA VARCHAR2 (35)NOT NULL,
NOMBRE_DECANO VARCHAR2 (35)NOT NULL,
CONSTRAINT PK_RES_AUX_SEL PRIMARY KEY (RESOLUCION_ID),
CONSTRAINT FK_ID_AUXILIAR_EN_RESOLUCION FOREIGN KEY (ID_AUXILIAR) REFERENCES AUXILIAR(AUX_ID),
CONSTRAINT FK_ID_TIPO_AUXILIAR_EN_RESOLUCION FOREIGN KEY (ID_TIPO_AUXILIAR) REFERENCES TIPO_AUXILIAR(TIPO_AUX_ID),
);
COMMENT ON TABLE RESOLUCION_AUXILIARES_SELECICONADOS IS 'Es la entidad que contiene los datos de las resoluciones de cada convocatoria.';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.RESOLUCION_ID IS 'Es la identificacion del auxiliar y la llave primaria.';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.DESCRIPCION IS 'Es la descripción del la resolución';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.ID_TIPO_AUXILIAR IS 'Es el tipo de auxiliar para el cual fue abierta la convocatoria';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.ID_AUXILIAR IS 'Es la identificacion del auxiliar seleccionado';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.PROMEDIO_AUXILIAR IS 'Es el promedio del auxiliar seleccionado.';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.HORAS_SEMESTRALES IS 'Es la cantidad de horas semestrales asignadas al auxiliar';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.VALOR_A_PAGAR IS 'Es le valor a pagar a cada auxiliar';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.NOMBRE_SOLICITANTE IS 'Es el nombre del solicitante de la convocatoria';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.NOMBRE_DIRECTOR_PROGRAMA IS 'Es el nombre director del programa';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.NOMBRE_DECANO IS 'Es el nombre del decano de la facultad';

CREATE TABLE DOCUMENTO_INCONFORMIDAD(
	DOC_INC_ID VARCHAR22(20) NOT NULL,
	FECHA_CREACION_DOC_INC DATE NOT NULL,
	DESCRIPCION VARCHAR22(255) NOT NULL,
	
	CONSTRAINT PK_DOCUMENTO_INCONFORMIDAD PRIMARY KEY (DOC_INC_ID)

);

CREATE TABLE DOCUMENTO_INCONFORMIDAD_AUXILIAR(
	ID_DOC_INC VARCHAR22(20) NOT NULL,
	ID_AUX VARCHAR22(20) NOT NULL,


	CONSTRAINT FK_AUXILIAR_EN_DOCUMENTO_INCONFORMIDAD_AUXILIAR FOREIGN KEY (ID_AUX) REFERENCES AUXILIAR (AUX_ID),
	CONSTRAINT FK_DOCUMENTO_INCONFORMIDAD_EN_DOCUMENTO_INCONFORMIDAD_AUXILIAR FOREIGN KEY (ID_DOC_INC) REFERENCES DOCUMENTO_INCONFORMIDAD (DOC_INC_ID)
);
