/* CONVENCIONES 
  TABLAS DE MAS DE 2 PALABRAS SE UTILIZAN LAS 3 PRIMERAS LETRAS DE CADA PALABRA PARA LA LLAVE PRIMARIA
  
  PARA LAS LLAVES FORANEAS SE UTILIZA LA SIGUIENTE SINTAXIS (CAMBIAR LO QUE ESTA EN MINUSCULA):
  FK_nombreTablaForanea_EN_TablaActual
  


*/


CREATE TABLE AUXILIAR(
AUX_ID VARCHAR2 (20) NOT NULL,
NOMBRE_AUX VARCHAR2 (50) NOT NULL,
APELLIDO_AUX VARCHAR2 (50) NOT NULL,
TELEFONO_AUX VARCHAR2 (20) NOT NULL, -- Falta normalizar Direccion, Programa académico--
CONSTRAINT PK_AUXILIAR PRIMARY KEY (AUX_ID)
);

COMMENT ON TABLE AUXILIAR IS 'Es la entidad que contiene los datos del auxiliar o estudiante que postula o puede observar las convocatorias.';
COMMENT ON COLUMN AUXILIAR.AUX_ID IS 'Es la identificacion del auxiliar y la llave primaria';
COMMENT ON COLUMN AUXILIAR.NOMBRE_AUX IS 'Es el nombre del auxiliar';
COMMENT ON COLUMN AUXILIAR.APELLIDO_AUX IS 'Es el apellido del auxiliar';
COMMENT ON COLUMN AUXILIAR.TELEFONO_AUX IS 'Es el telefono del auxiliar';

CREATE TABLE SOLICITANTE (
SOL_ID VARCHAR2 (20) NOT NULL,
NOMBRE_SOL VARCHAR2 (50) NOT NULL,
APELLIDO_SOL VARCHAR2 (50) NOT NULL,
TELEFONO_SOL VARCHAR2 (20) NOT NULL,--Falta normalizar area - Cargo - Direccion
CONSTRAINT PK_SOL PRIMARY KEY (SOL_ID),
);
COMMENT ON TABLE SOLICITANTE IS 'Es la entidad que contiene los datos del solicitante quien describe la necesidad del auxiliar.';
COMMENT ON COLUMN SOLICITANTE.SOL_ID IS 'Es la identificacion del solicitante y la llave primaria';
COMMENT ON COLUMN SOLICITANTE.NOMBRE_SOL IS 'Es el nombre del solicitante';
COMMENT ON COLUMN SOLICITANTE.APELLIDO_SOL IS 'Es el apellido del solicitante';
COMMENT ON COLUMN SOLICITANTE.TELEFONO_SOL IS 'Es el telefono del solicitante';

CREATE TABLE PROGRAMA_ACADEMICO(
  PRO_ACA_ID VARCHAR2(20) NOT NULL,
  NOMBRE_PRO_ACA VARCHAR2(50) NOT NULL,
  ID_FACULTAD VARCHAR2(2) NOT NULL,
  
  CONSTRAINT PK_PROGRAMA_ACADEMICO PRIMARY KEY (PRO_ACA_ID),
  CONSTRAINT FK_FACULTAD_EN_PROGRAMA_ACADEMICO FOREIGN KEY (ID_FACULTAD) REFERENCES FACULTAD (FACULTAD_ID)
);

CREATE TABLE FACULTAD(
  FACULTAD_ID VARCHAR2(2) NOT NULL,
  NOMBRE_FACULTAD VARCHAR2(50) NOT NULL,
  ID_UNIVERSIDAD VARCHAR2(5) NOT NULL,
  
  CONSTRAINT PK_FACULTAD PRIMARY KEY (ID_UNIVERSIDAD),
  CONSTRAINT FK_UNIVERSIDAD_EN_FACULTAD FOREIGN KEY (ID_UNIVERSIDAD) REFERENCES UNIVERSIDAD (UNIVERSIDAD_ID)
);


CREATE TABLE UNIVERSIDAD(
  UNIVERSIDAD_ID Varchar (20) NOT NULL,
  NOMBRE_UNIVERSIDAD VARCHAR (20) NOT NULL,
  
  CONSTRAINT PK_UNIVERSIDAD PRIMARY KEY (UNIVERSIDAD_ID)
);


CREATE TABLE HORARIO_ACTIVIDADES (
HOR_ACT_ID VARCHAR (20) NOT NULL,
FECHA_CREACION_HOR_ACT DATE NOT NULL,
ID_TIPO_AUX VARCHAR (20),
ID_AUXILIAR VARCHAR (20) NOT NULL,

CONSTRAINT PK_HORARIO_ACTIVIDADES PRIMARY KEY (HOR_ID),
CONSTRAINT FK_TIPO_AUXILIARES_EN_HORARIO_ACTIVIDADES FOREIGN KEY (ID_TIPO_AUX) REFERENCES TIPO_AUXILIAR (TIP_AUX), 
CONSTRAINT FK_ID_AUXILIAR_EN_HORARIO_ACTIVIDADES FOREIGN KEY (ID_AUXILIAR) REFERENCES AUXILIAR (AUX_ID)
);

CREATE TABLE FECHA_HORARIO (
FEC_HOR_ID VARCHAR (20) NOT NULL,
FECHA_FEC_HOR DATE NOT NULL,
ID_HOR_ACT VARCHAR (20) NOT NULL,
CONSTRAINT PK_FECHA_HORARIO PRIMARY KEY (FEC_HOR_ID),
CONSTRAINT FK_HORARIO_ACTIVIDADES_EN_FECHA_HORARIO FOREIGN KEY (ID_HOR_ACT) REFERENCES HORARIO_ACTIVIDADES (HOR_ACT_ID)
);

CREATE TABLE HORA (
HOR_ID VARCHAR (20) NOT NULL,
HORA_HOR VARCHAR (20) NOT NULL,
ID_FECHA_HORARIO VARCHAR (20) NOT NULL,
CONSTRAINT PK_HORA PRIMARY KEY (HOR_ID),
CONSTRAINT FK_FECHA_HORARIO_EN_HORA FOREIGN KEY (ID_FECHA_HORARIO) REFERENCES FECHA_HORARIO (FEC_HOR_ID)
);

CREATE TABLE TIPO_AUXILIAR (
TIP_AUX_ID VARCHAR (20) NOT NULL,
DESCRIPCION_TIP_AUX VARCHAR (30) NOT NULL,
CONSTRAINT PK_TIPO_AUXILIAR PRIMARY KEY (TIP_AUX_ID)
);

RESOLUCION_AUXILIARES_SELECICONADOS(
RESOLUCION_ID VARCHAR (20) NOT NULL
DESCRIPCION VARCHAR (255) NOT NULL,
ID_TIPO_AUXILIAR VARCHAR (20) NOT NULL,
ID_AUXILIAR VARCHAR2 (20) NOT NULL,
PROMEDIO_AUXILIAR VARCHAR (20) NOT NULL,
HORAS_SEMESTRALES VARCHAR (2) NOT NULL,
VALOR_A_PAGAR VARCHAR (7) NOT NULL,
NOMBRE_SOLICITANTE VARCAHR (35) NOT NULL,
NOMBRE_DIRECTOR_PROGRAMA VARCHAR (35)NOT NULL,
NOMBRE_DECANO VARCHAR (35)NOT NULL,
CONSTRAINT PK_RES_AUX_SEL PRIMARY KEY (RESOLUCION_ID),
CONSTRAINT FK_ID_AUXILIAR_EN_RESOLUCION FOREIGN KEY (ID_AUXILIAR) REFERENCES AUXILIAR(AUX_ID),
CONSTRAINT FK_ID_TIPO_AUXILIAR_EN_RESOLUCION FOREIGN KEY (ID_TIPO_AUXILIAR) REFERENCES TIPO_AUXILIAR(TIPO_AUX_ID),
);
COMMENT ON TABLE RESOLUCION_AUXILIARES_SELECICONADOS IS 'Es la entidad que contiene los datos de las resoluciones de cada convocatoria.';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.RESOLUCION_ID IS 'Es la identificacion del auxiliar y la llave primaria.';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.DESCRIPCION IS 'Es la descripción del la resolución';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.ID_TIPO_AUXILIAR IS 'Es el tipo de auxiliar para el cual fue abierta la convocatoria';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.ID_AUXILIAR IS 'Es la identificacion del auxiliar seleccionado';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.PROMEDIO_AUXILIAR IS 'Es el promedio del auxiliar seleccionado.';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.HORAS_SEMESTRALES IS 'Es la cantidad de horas semestrales asignadas al auxiliar';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.VALOR_A_PAGAR IS 'Es le valor a pagar a cada auxiliar';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.NOMBRE_SOLICITANTE IS 'Es el nombre del solicitante de la convocatoria';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.NOMBRE_DIRECTOR_PROGRAMA IS 'Es el nombre director del programa';
COMMENT ON COLUMN RESOLUCION_AUXILIARES_SELECICONADOS.NOMBRE_DECANO IS 'Es el nombre del decano de la facultad';

CREATE TABLE DOCUMENTO_INCONFORMIDAD(
	DOC_INC_ID VARCHAR2(20) NOT NULL,
	FECHA_CREACION_DOC_INC DATE NOT NULL,
	DESCRIPCION VARCHAR2(255) NOT NULL,
	

	CONSTRAINT PK_DOCUMENTO_INCONFORMIDAD PRIMARY KEY (DOC_INC_ID)

);

CREATE TABLE DOCUMENTO_INCONFORMIDAD_AUXILIAR(
	ID_DOC_INC VARCHAR2(20) NOT NULL,
	ID_AUX VARCHAR2(20) NOT NULL,


	CONSTRAINT FK_AUXILIAR_EN_DOCUMENTO_INCONFORMIDAD_AUXILIAR FOREIGN KEY (ID_AUX) REFERENCES AUXILIAR (AUX_ID),
	CONSTRAINT FK_DOCUMENTO_INCONFORMIDAD_EN_DOCUMENTO_INCONFORMIDAD_AUXILIAR FOREIGN KEY (ID_DOC_INC) REFERENCES DOCUMENTO_INCONFORMIDAD (DOC_INC_ID)
);
